### ISSUE TITLE
pip install fail

### ISSUE THREAD

**Issue by Xgl0baltk** [njwidmann/CADLasso#1]
so i have run into this issue on Windows 10 running the Powershell:

PS D:\CADLasso> pip install requirements.txt
ERROR: Could not find a version that satisfies the requirement requirements.txt
ERROR: No matching distribution found for requirements.txt

it sounds so simple in the readme. 
![image](https://user-images.githubusercontent.com/59404282/111553555-f32a4a80-8784-11eb-9d94-6d7cc817e043.png)

**Comment by njwidmann** [comment]
I would make sure your pip is updated and also try just manually installing all of the libraries listed in requirements.txt. There aren't too many.

**Comment by Xgl0baltk** [comment]
ok so there is a -r missing apparently if it is not my pip being weird =) if it's applicable maybe as an update in the description.
Opencv is now  opencv_python-4.5.1.48-cp39-cp39-win_amd64.whl (34.9 MB) 

![image](https://user-images.githubusercontent.com/59404282/111666990-8bbbdb80-8814-11eb-8157-c66559eb8b6c.png)
